### ISSUE TITLE
Error when using JsonMessageSerializer with default settings

### ISSUE THREAD

**Issue by robert94p** [zarusz/SlimMessageBus#252]
if you use JsonMessageSerializer in web api aplication with default settings, an error is thrown

` System.InvalidOperationException: Serializer options cannot be changed once serialization or deserialization has occurred..
    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerOptionsImmutable(JsonSerializerContext context)
   at System.Text.Json.Serialization.ConverterList.Add(JsonConverter item)
   at SlimMessageBus.Host.Serialization.SystemTextJson.JsonMessageSerializer..ctor(JsonSerializerOptions options)
   at SlimMessageBus.Host.Serialization.SystemTextJson.SerializationBuilderExtensions.<>c__DisplayClass0_0`1.<AddJsonSerializer>b__1(IServiceProvider svp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)`

https://github.com/zarusz/SlimMessageBus/blob/master/src/SlimMessageBus.Host.Serialization.SystemTextJson/JsonMessageSerializer.cs#L24

**Comment by robert94p** [comment]
I'm using 2.3.2 version

**Comment by zarusz** [comment]
@robert94p the issue should be fixed in the [2.3.3](https://www.nuget.org/packages/SlimMessageBus.Host.Serialization.SystemTextJson/2.3.3) version.

Feel free to re-open the issue if you still run into the error.
