### ISSUE TITLE
[Host.Mqtt] A channel must be set.

### ISSUE THREAD

**Issue by Ziocash** [zarusz/SlimMessageBus#326]
Could be MQTTnet related.

Context: I'm using it in a Worker Service for communication with another application

Library version: **2.5.3**

```cs
#region SlimMessageBus
services.AddSlimMessageBus(mbb =>
{
    mbb.WithProviderMqtt((config) =>
    {
        config.ClientBuilder
            .WithClientId("SubscriptionWorker")
            .WithTcpServer("127.0.0.1") //tried with 127.0.0.1 and localhost
            .WithKeepAlivePeriod(TimeSpan.FromSeconds(30))
            .WithWillQualityOfServiceLevel(MqttQualityOfServiceLevel.ExactlyOnce)
            .WithProtocolVersion(MqttProtocolVersion.V500);
    });
    mbb.Produce<Subscription>(x => x.DefaultTopic(TopicNames.CheckedSub))
        .Consume<Subscription>(x => x.Topic(TopicNames.CheckSub)
        .WithConsumer<SubscriptionConsumer>());
});
#endregion

services.AddSingleton<IMasterMessageBus, MqttMessageBus>();
services.AddSingleton<MqttMessageBusSettings>();
```

Following all the guides I found I get this error

```
System.InvalidOperationException: A channel must be set.
   at MQTTnet.Client.MqttClientOptionsBuilder.Build()
   at SlimMessageBus.Host.Mqtt.MqttMessageBus.OnStart()
   at SlimMessageBus.Host.MessageBusBase.Start()
   at SlimMessageBus.Host.MessageBusHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

I'm using this as a simple channel for communication with MQTT, technically it's set up correctly.

I suppose there's something strange with ClientBuilder initialization.

**Comment by zarusz** [comment]
Hello,

Can you please try to remove the following registrations to the SMB internals and give it a try? Having it might corrupt the way how instances are managed. This types are registered inside the AddSlimMessageBus() and users should not override.


> services.AddSingleton<IMasterMessageBus, MqttMessageBus>();
> services.AddSingleton<MqttMessageBusSettings>();

If that does not work. Please report and I can see the integration tests and sample.

**Comment by Ziocash** [comment]
I'll tried your solution and it worked properly, maybe I followed an old guide.

Thank you for your help.

**Comment by Ziocash** [comment]
Fixed removing services registration

```cs
#region SlimMessageBus
services.AddSlimMessageBus(mbb =>
{
    mbb.WithProviderMqtt((config) =>
    {
        config.ClientBuilder
            .WithClientId("SubscriptionWorker")
            .WithTcpServer("127.0.0.1") //tried with 127.0.0.1 and localhost
            .WithKeepAlivePeriod(TimeSpan.FromSeconds(30))
            .WithWillQualityOfServiceLevel(MqttQualityOfServiceLevel.ExactlyOnce)
            .WithProtocolVersion(MqttProtocolVersion.V500);
    });
    mbb.Produce<Subscription>(x => x.DefaultTopic(TopicNames.CheckedSub))
        .Consume<Subscription>(x => x.Topic(TopicNames.CheckSub)
        .WithConsumer<SubscriptionConsumer>());
});
#endregion
```

**Comment by zarusz** [comment]
Glad it worked. Have fun using it!
