### ISSUE TITLE
LogManager.cs not found

### ISSUE THREAD

**Issue by thunh1710** [zarusz/SlimMessageBus#4]
While I was running your tests, I detected a error
"LogManager.cs not found"

**Comment by zarusz** [comment]
Hi, 

Can you please provide more details: 
* How are you running these tests?
* What branch are you using?
* Which tests specifically?
* Maybe provide the full error?

Cheers,

**Comment by zarusz** [comment]
Hi,

Thanks for the additional info - that helped me pin point the issue.

With some recent refactor the log statement put wrong number of placeholders in the text template - it was logging the error when message publishing failed. With my latest commit it should now be fixed - please check it out. The fact that VS said AbstractLogger.cs not found, was I believe due to it trying to show you source of Commong.Logging where it throws that number of params mismatch.

I suspect that you were getting an publication failure. To double check please note the test requires two topics `test-ping` and `test-echo` and specifically it requires them two have 2 partitions. If you didn't create the topics with 2 partition before then you will see (with the fix I put in) an exception from the Kafka client library (librdkafka):
```
{Confluent.Kafka.KafkaException: Local: Unknown partition
   at Confluent.Kafka.Producer.Produce(String topic, Byte[] val, Int32 valOffset, Int32 valLength, Byte[] key, Int32 keyOffset, Int32 keyLength, Nullable`1 timestamp, Int32 partition, Boolean blockIfQueueFull, IDeliveryHandler deliveryHandler)
   at Confluent.Kafka.Producer.ProduceAsync(String topic, Byte[] key, Int32 keyOffset, Int32 keyLength, Byte[] val, Int32 valOffset, Int32 valLength, Int32 partition)
   at SlimMessageBus.Host.Kafka.KafkaMessageBus.PublishToTransport(Type messageType, Object message, String topic, Byte[] payload) in C:\Users\tomasz\dev\mygithub\SlimMessageBus\src\SlimMessageBus.Host.Kafka\KafkaMessageBus.cs:line 194
   at SlimMessageBus.Host.MessageBusBase.SendInternal[TResponseMessage](IRequestMessage`1 request, Nullable`1 timeout, String topic, CancellationToken cancellationToken) in C:\Users\tomasz\dev\mygithub\SlimMessageBus\src\SlimMessageBus.Host\MessageBusBase.cs:line 216}
```

I added some remarks on the test, so that its more clear it requires topics with two partitions.

```
bin\windows\kafka-topics.bat --create --zookeeper localhost:2181 --partitions 2 --replication-factor 1 --topic test-ping
bin\windows\kafka-topics.bat --create --zookeeper localhost:2181 --partitions 2 --replication-factor 1 --topic test-echo
```

Please let me know if you still run into any issues.

Cheers,

**Comment by zarusz** [comment]
Hi @thunh1710, is this now resolved for you?

**Comment by zarusz** [comment]
Closing due to inactivity. Please reopen if needed.
